### ISSUE TITLE
[CRITICAL] Broken template

### ISSUE THREAD

**Issue by holinov** [zio/zio-project-seed.g8#27]
I'm unable to create new project using template( 
I'm using macosx catalina 10.15.6
```
$ mkdir zmatters                                                                                                                                                            
$ cd zmatters                                                                                                                                                               
$ sbt new zio/zio-project-seed.g8     
[info] welcome to sbt 1.3.12 (Oracle Corporation Java 11.0.2)
[info] loading global plugins from /Users/alberthofmann/.sbt/1.0/plugins
[info] set current project to zmatters (in build file:/Users/alberthofmann/src/scala/zmatters/)
[info] set current project to zmatters (in build file:/Users/alberthofmann/src/scala/zmatters/)
name [ZIO Project]: zmatters

Exiting due to error in the template: /var/folders/yk/sw1brrtx1vb8sjv0wg_74y3r0000gn/T/giter8-2113315225506566
File: /var/folders/yk/sw1brrtx1vb8sjv0wg_74y3r0000gn/T/giter8-2113315225506566/src/main/g8/project/BuildHelper.scala, 215:22: '",
    crossScalaVersions := Seq(Scala211, Scala212, Scala213),
    scalaVersion in ThisBuild := Scala212,
    scalacOptions := stdOptions ++ extraOptions(scalaVersion.value, optimize = !isSnapshot.value),
    libraryDependencies ++= {
      if (isDotty.value)
        Seq(
          ("' came as a complete surprise to me

```

**Comment by sidnt** [comment]
same issue

**Comment by mtk** [comment]
just saw this.  not sure if it is part of the same problem?

% sbt new zio/zio-project-seed.g8
[info] welcome to sbt 1.3.13 (Red Hat, Inc. Java 15)
[info] loading settings for project global-plugins from sbt-native-packager.sbt,sbt-jmh.sbt,sbt-dotty.sbt,sbt-github-packages.sbt,sbt-scalafmt.sbt,sbt-coverage.sbt,sbt-missinglink.sbt,idea.sbt,sbt-native-image.sbt,sbt-metals.sbt,sbt-explicitDependences.sbt,sbt-updates.sbt,sbt-scalafix.sbt ...
[info] loading global plugins from /home/mtk/.sbt/1.0/plugins
[info] set current project to tmp (in build file:/home/mtk/tmp/)
[info] set current project to tmp (in build file:/home/mtk/tmp/)
[warn] undefined keys `githubOwner` and `githubRepository`
[warn] retaining pre-existing publication settings
name [ZIO Project]: zfoo

Exiting due to error in the template: /tmp/giter8-101164085751696
File: /tmp/giter8-101164085751696/src/main/g8/project/BuildHelper.scala, An unexpected error occurred while processing the template. Check that all literal '$' are properly escaped with '\$'
